### PR TITLE
New Loader, Orbital Spinner

### PR DESCRIPTION
**Pull request by break7533**
Maybe this is a bit much from what you were asking for help. I found your repo on this issue of the [React Status newsletter](https://react.statuscode.com/issues/155).

It is a new component spinner, I only added the colour option, but I intend to also add the sizing prop.

Hope you like it! 👍

### CODE REVIEW

**Comment by JoshK2** [comment]
Thanks!, It's looking very good and original, I like it. 😃

**Comment by JoshK2** [comment]
Hey @break7533, I added your spinner also in the Angular project!
https://github.com/JoshK2/ng-spinners/tree/master/lib/components/orbitals-loader

And I 'll add it also in the Vue project next week.

**Comment by break7533** [comment]
Uau, that is really cool! thanks!! 👍

**Comment by JoshK2** [comment]
@break7533 I just want to tell you that I also added your spinner in the Vue project!
https://github.com/JoshK2/vue-spinners-css/blob/master/src/components/OrbitalsLoader.vue

So thank's a lot for your contribution.

**Comment by break7533** [comment]
Awesome, thank you! 😄

**Pull request merged**
