### PR TITLE
Feature/double ring size

### PR DESCRIPTION
**Pull request by break7533**
Added sizing to the double ring component. Now it accepts a size prop.

Btw, should I change the read me to reflect these changes or do you prefer to be responsible to the changes on the README file?

### CODE REVIEW

**Comment by JoshK2** [comment]
Thanks for this contribution!😃
I'll update the README, but next time you can update it also.

**Comment by break7533** [comment]
Sure thing, I might do some more today and I will update the Readme and the contributing guidelines to add that info! 😃

**Comment by JoshK2** [comment]
I update today the contributing guidelines.

**Comment by JoshK2** [comment]
I just updated the README and the CONTRIBUTING files.

**Comment by break7533** [comment]
Cool, I already updated the repo on my side with your changes! :) thanks!

**Pull request merged**
